### ISSUE TITLE
Khá nhiều bug với cờ :)

### ISSUE THREAD

**Issue by 3multid** [tuanasanhuvacode/hackathon-N44#6]
1. Số cờ về 0 thì vẫn cắm được cờ và số cờ xuống âm
2. (1 số lần) Khi cắm cờ xung quanh 1 ô 0, mở ô 0 đó, xóa 1 cờ xung quanh mà ở ô có cờ đó là số 0 và mở ô 0 thứ 2 đó thì tự thua

**Comment by TrungNguyen1909** [comment]
1. Số cờ âm là intended

**Comment by TrungNguyen1909** [comment]
2. Fixed upon 0.2.2 release
